version: "3.9"

services:
  app:
    build:
      # Build the docker file in current directory
      context: .
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./app:./app
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    # Run in terminal = docker-compose build