---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # "uses" utilises a preconfigured git action pipeline provided by Docker to login in Docker hub
        # uses: docker/login-action@v1
        # with:
        #   username: ${{ secrets.DOCKERHUB_USER }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Checkout
        # Provided by Github to checkout our code
        uses: actions/checkout@v2

      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Linter
        run: docker-compose run --rm app sh -c "flake8"